version: "3.7"

#Volumes
volumes:
  dbdata:
    driver: local

services:
    # image project
    app:
        container_name: selise-task--app
        build:
            context: .
            dockerfile: ./.docker/php/Dockerfile
        image: selise-task-app-image
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        depends_on: 
            - redis
        networks: 
            - selise-task-net
    
    # nginx
    nginx:
        container_name: selise-task-nginx
        image: nginx:alpine
        restart: unless-stopped
        ports: 
            - "8983:80"
        volumes: 
            - ./:/var/www
            - ./.docker/nginx/:/etc/nginx/conf.d/
        networks: 
            - selise-task-net

    # db mysql
    mysql:
        image: mysql:8.0.28
        restart: unless-stopped
        tty: true
        environment: 
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_HOST: '%'
        volumes: 
            - ./.docker/mysql/my.cnf:/etc/my.cnf
            - dbdata:/var/lib/mysql/
        ports: 
            - "3383:3306"
        networks: 
            - selise-task-net

    # queue
    queue:
        container_name: selise-task-queue
        image: selise-task-app-image
        restart: unless-stopped
        command: "php artisan queue:work"
        volumes: 
            - ./:/var/www
        depends_on: 
            - redis
            - app
        networks: 
            - selise-task-net

    # redis
    redis:
        container_name: selise-task-redis
        image: redis:latest
        volumes:
            - ./redis-data:/data
        healthcheck:
            test: "echo redis ok"
        networks: 
            - selise-task-net

networks: 
    selise-task-net:
        driver: bridge